### ISSUE TITLE
Hardcoded extension key in ext_emconf.php 

### ISSUE THREAD

**Issue by mischka** [TYPO3/CmsComposerInstallers#49] opened 2016-05-11 10:00 UTC
If the extension name is hardcoded in the ext_emconf.php file, the getEmConfMetaData method throws an Undefined index exception. Because the access via $EM_CONF[$_EXTKEY] won't work.

hardcoded extkey

    $EM_CONF['my_ext'] = array(
       ...
    );

extkey via variable

    $EM_CONF[$_EXTKEY] = array(
       ...
    );

The Problem is: `$_EXTKEY = basename($path);` this doesn't work with hardcoded extkeys.

**Comment by helhum** [comment] 2016-05-11 10:30
> The Problem is: $_EXTKEY = basename($path); this doesn't work with hardcoded extkeys.

Sorry, but the problem is hardcoded extkeys in ext_emconf.php. This needs to be fixed in the extension, not in the composer installer.

**Closed by helhum** 2016-05-11 10:30 UTC
