### ISSUE TITLE
Option to skip symlinks and directory structure

### ISSUE THREAD

**Issue by timofloettmann** [TYPO3/CmsComposerInstallers#38] opened 2016-03-09 11:16 UTC
I'm hoping to switch to a fully composer based typo3 installation soon. Meaning I'd add a composer.json to my repository and include some of my dev-dependencies as well as typo3/cms and all the external extensions via composer.

Whenever I run _composer install_ locally however, the installer creates symlinks and directories that mess with the directory structure within my repository. I don't like that very much. It's good for production, but not for local development.
The best case for me would be that everything gets installed under vendor/ in development mode (= composer install without --no-dev) and symlinks etc. are only created in production (when --no-dev is provided).

Personally I'd like to have a config-setting that enables this and then uses the --no-dev flag to determine the desired behaviour. 

Any thoughts? Is there already a way to do something like this?

**Comment by helhum** [comment] 2016-03-09 15:58
Like suggested in #21 already, an option which disables symlink creation is indeed viable and planned. Pull requests are welcome as well. When creating a pull request, #35 may be good to be taken into account.

I close this ticket now as duplicate of #21

**Closed by helhum** 2016-03-09 15:58 UTC
