### ISSUE TITLE
Improve usability: fail gracefully on existing symlinks

### ISSUE THREAD

**Issue by 7elix** [TYPO3/CmsComposerInstallers#57] opened 2016-08-24 13:35 UTC
Hi Helmut,

the composer installer fails with fatal in case web/index.php or web/typo3 already exist.
Do you see a reason for the fatal in case the symlinks are set up correctly?

I think about adding a second check to Filsystem->symlink checks beside file_exists that compare the current symlink target to the intended symlink target.

Good or nah?

```
    public function symlink($source, $target, $copyOnFailure = true, $makeRelative = true)
    {
        if (!file_exists($source)) {
            throw new \InvalidArgumentException('The symlink source "' . $source . '" is not available.');
        }
        if (file_exists($target)) {
            throw new \InvalidArgumentException('The symlink target "' . $target . '" already exists.');

```

**Comment by helhum** [comment] 2016-08-29 09:47
> I think about adding a second check to Filsystem->symlink checks beside file_exists that compare the current symlink target to the intended symlink target.
> Good or nah?

Yes, would be a good idea in general.

Things to consider:

* Getting the target of a symlink is surprisingly difficult across platform (Windows)
* What should be done, if the target is not a symlink, but a file/ folder?
* For the future I would like to get rid of symlinking altogether and write files instead

@7elix are you interested in helping out in this area?

**Comment by helhum** [comment] 2016-09-01 20:15
oh, btw. this is a duplicate of #35

I close this as duplicate

**Closed by helhum** 2016-09-01 20:15 UTC
